import type { ModelCapabilities } from '@opencodex/core';

const KNOWN: ReadonlyArray<ModelCapabilities> = [
  {
    id: 'gpt-4o',
    providerId: 'openai',
    displayName: 'GPT-4o',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    toolUse: true,
    vision: true,
    streaming: true,
    embeddings: false,
    promptCaching: true,
    pricing: { inputPerMillion: 2.5, outputPerMillion: 10, cachedInputPerMillion: 1.25 },
  },
  {
    id: 'gpt-4o-mini',
    providerId: 'openai',
    displayName: 'GPT-4o mini',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    toolUse: true,
    vision: true,
    streaming: true,
    embeddings: false,
    promptCaching: true,
    pricing: { inputPerMillion: 0.15, outputPerMillion: 0.6, cachedInputPerMillion: 0.075 },
  },
  {
    id: 'gpt-4.1',
    providerId: 'openai',
    displayName: 'GPT-4.1',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    toolUse: true,
    vision: true,
    streaming: true,
    embeddings: false,
    promptCaching: true,
    pricing: { inputPerMillion: 2, outputPerMillion: 8, cachedInputPerMillion: 0.5 },
  },
  {
    id: 'gpt-4.1-mini',
    providerId: 'openai',
    displayName: 'GPT-4.1 mini',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    toolUse: true,
    vision: true,
    streaming: true,
    embeddings: false,
    promptCaching: true,
    pricing: { inputPerMillion: 0.4, outputPerMillion: 1.6, cachedInputPerMillion: 0.1 },
  },
  {
    id: 'o1',
    providerId: 'openai',
    displayName: 'o1',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    toolUse: true,
    vision: true,
    streaming: true,
    embeddings: false,
    reasoning: true,
    pricing: { inputPerMillion: 15, outputPerMillion: 60, cachedInputPerMillion: 7.5 },
  },
  {
    id: 'o3-mini',
    providerId: 'openai',
    displayName: 'o3-mini',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    toolUse: true,
    vision: false,
    streaming: true,
    embeddings: false,
    reasoning: true,
    pricing: { inputPerMillion: 1.1, outputPerMillion: 4.4, cachedInputPerMillion: 0.55 },
  },
  {
    id: 'text-embedding-3-small',
    providerId: 'openai',
    displayName: 'text-embedding-3-small',
    contextWindow: 8_191,
    toolUse: false,
    vision: false,
    streaming: false,
    embeddings: true,
    pricing: { inputPerMillion: 0.02, outputPerMillion: 0 },
  },
  {
    id: 'text-embedding-3-large',
    providerId: 'openai',
    displayName: 'text-embedding-3-large',
    contextWindow: 8_191,
    toolUse: false,
    vision: false,
    streaming: false,
    embeddings: true,
    pricing: { inputPerMillion: 0.13, outputPerMillion: 0 },
  },
];

export function knownModels(): ModelCapabilities[] {
  return KNOWN.map((m) => ({ ...m }));
}

export function findModel(id: string): ModelCapabilities | undefined {
  return KNOWN.find((m) => m.id === id);
}
